/│\|Table /! s/2ν″/_2_nu_double_prime/g
/│\|Table /! s/(Vₒ+u)/equilibriumArgument/g
/│\|Table /! s/α/alpha/g
/│\|Table /! s/Δ/DELTA/g
/│\|Table /! s/ν/nu/g
/│\|Table /! s/ξ/xi/g
/│\|Table /! s/λ/lambda/g
/│\|Table /! s/ω/omega/g
/│\|Table /! s/Ω/OMEGA/g
/│\|Table /! s/ₐ/a/g
/│\|Table /! s/ᵤ/u/g
/│\|Table /! s/′/_prime/g
/│\|Table \|tab14/! s/₁/1/g
/│\|Table \|tab14/! s/₂/2/g
/│\|Table \|tab14/! s/₃/3/g
